module.exports = {
    "halfpast": "Half past {{hourInWord|lowerCase}}",
    "midnight": "Midnight",
    "oclock": "{{hourInWord}} o'clock",
    "minutepast": "{{minuteInWord}} past {{hourInWord|lowerCase}}",
    "minuteto": "{{minuteRemainInWord}} to {{hourNextInWord|lowerCase}}",
    "numberInWord": [
        "Midnight",
        "One",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six",
        "Seven",
        "Eight",
        "Nine",
        "Ten",
        "Eleven",
        "Twelve",
        "Thirteen",
        "Fourteen",
        "Quarter",
        "Sixteen",
        "Seventeen",
        "Eighteen",
        "Nineteen",
        "Twenty",
        "Twenty one",
        "Twenty two",
        "Twenty three",
        "Twenty four",
        "Twenty five",
        "Twenty six",
        "Twenty seven",
        "Twenty eight",
        "Twenty nine"
    ]
}