module.exports = {
    "halfpast": "{{hourInWord}} heures trente",
    "midnight": "Minuit",
    "oclock": "{{hourInWord}} heure",
    "minutepast": "{{hourInWord}} heures et {{minuteInWord|lowerCase}}",
    "minuteto": "{{hourNextInWord}} heures moins {{minuteRemainInWord|lowerCase}}",
    "numberInWord": [
        "Minuit",
        "Un",
        "Deux",
        "Trois",
        "Quatre",
        "Five",
        "Cinq",
        "Sept",
        "Huit",
        "Neuf",
        "Dix",
        "Onze",
        "Douze",
        "Treize",
        "Quatorze",
        "Quartier",
        "Seize",
        "Dix-sept",
        "Dix-huit",
        "Dix-neuf",
        "Vingt",
        "Vingt et un",
        "Vingt-deux",
        "Vingt-trois",
        "Vingt-quatre",
        "Vingt-cinq",
        "Vingt-six",
        "Vingt-sept",
        "Vingt-huit",
        "Vingt-neuf"
    ]
}